// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuF511RHQIemvC1h0btbphnTbD4UVyeMw',
    appId: '1:440505053659:web:589e14b80995e5ba56f7fe',
    messagingSenderId: '440505053659',
    projectId: 'contacts-app-d1d9f',
    authDomain: 'contacts-app-d1d9f.firebaseapp.com',
    storageBucket: 'contacts-app-d1d9f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBob8pULiO8U_TmPjkK2c8Qig-4V-fxpho',
    appId: '1:440505053659:android:45c3c944acd253d956f7fe',
    messagingSenderId: '440505053659',
    projectId: 'contacts-app-d1d9f',
    storageBucket: 'contacts-app-d1d9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1sD2_M-G7mTBSJT_Ag4CqMpLLM4IIdu4',
    appId: '1:440505053659:ios:7bbebb687236677656f7fe',
    messagingSenderId: '440505053659',
    projectId: 'contacts-app-d1d9f',
    storageBucket: 'contacts-app-d1d9f.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1sD2_M-G7mTBSJT_Ag4CqMpLLM4IIdu4',
    appId: '1:440505053659:ios:7bbebb687236677656f7fe',
    messagingSenderId: '440505053659',
    projectId: 'contacts-app-d1d9f',
    storageBucket: 'contacts-app-d1d9f.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuF511RHQIemvC1h0btbphnTbD4UVyeMw',
    appId: '1:440505053659:web:d02476b4cc4f32cc56f7fe',
    messagingSenderId: '440505053659',
    projectId: 'contacts-app-d1d9f',
    authDomain: 'contacts-app-d1d9f.firebaseapp.com',
    storageBucket: 'contacts-app-d1d9f.firebasestorage.app',
  );
}
